project:
  type: website
  output-dir: docs

website:
  title: "Computational Biology Research Group"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: publications.qmd
        text: Publications
      - href: collaborations.qmd
        text: Collaborations
      - href: team.qmd
        text: Team
      - href: contact.qmd
        text: Contact
      
      
      

  page-footer:
    left: "Computational Biology Research Group — School of Microbiology, Universidad de Antioquia"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true